name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish App on Google Play
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v2
      # Decrypt secrets
      - name: Decrypt secrets folder
        run: ./.github/scripts/decrypt_secrets.sh
        env:
          SECRETS_GPG_PASSPHRASE: ${{ secrets.SECRETS_GPG_PASSPHRASE }}
      # Set up Java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Restore Cache
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - name: Cache Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Cache Android Gradle Plugin
        uses: actions/cache@v1
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-android-gradle-cache-
      # Build and deploy
      - name: Build and publish app on Google Play
        run: ./gradlew publishReleaseBundle --stacktrace
        env:
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASS: ${{ secrets.RELEASE_KEY_PASS }}
          RELEASE_KEY_STORE_PASS: ${{ secrets.RELEASE_KEY_STORE_PASS }}
      # Notify Slack
      - name: Slack success notification
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"#mobile-android\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\":android: *Publish App on Google Play* :+1:\"}},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{ github.repository }}/actions|${{ github.repository }}>\"}]}],\"attachments\":[{\"blocks\":[{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Commit:*\n<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>\"},{\"type\":\"mrkdwn\",\"text\":\"*Author:*\n${{ github.event.head_commit.author.name }}\"}]}],\"color\":\"good\"}]}'
      - name: Slack failure notification
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"#mobile-android\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\":android: *Publish App on Google Play* :fire:\"}},{\"type\":\"context\",\"elements\":[{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${{ github.repository }}/actions|${{ github.repository }}>\"}]}],\"attachments\":[{\"blocks\":[{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Commit:*\n<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>\"},{\"type\":\"mrkdwn\",\"text\":\"*Author:*\n${{ github.event.head_commit.author.name }}\"}]}],\"color\":\"danger\"}]}'
